// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebBanHang.Models;

namespace WebXeDo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240626111228_KhoiTao")]
    partial class KhoiTao
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.17")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebBanHang.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DisplayOrder = 1,
                            Name = "Yamaha"
                        },
                        new
                        {
                            Id = 2,
                            DisplayOrder = 2,
                            Name = "Honda"
                        },
                        new
                        {
                            Id = 3,
                            DisplayOrder = 3,
                            Name = "Suzuki"
                        });
                });

            modelBuilder.Entity("WebBanHang.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KhachHangName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("WebBanHang.Models.OrderDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductId");

                    b.ToTable("orderDetails");
                });

            modelBuilder.Entity("WebBanHang.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Exciter 135 62zz",
                            Price = 300.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Exciter 135 65zz",
                            Price = 350.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Exciter 135 68zz",
                            Price = 400.0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 1,
                            Name = "Exciter 135 72+4",
                            Price = 420.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Exciter 150 62zz",
                            Price = 630.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "Exciter 150 65zz",
                            Price = 750.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Name = "Exciter 150 72z6",
                            Price = 820.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Name = "Exciter 150 68z8",
                            Price = 950.0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 2,
                            Name = "Winner V1 62zz",
                            Price = 1200.0
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 2,
                            Name = "Winner V1 65zz ",
                            Price = 1450.0
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 2,
                            Name = "Winner X v1 68z6",
                            Price = 750.0
                        },
                        new
                        {
                            Id = 12,
                            CategoryId = 2,
                            Name = "Winner X v2 65zz",
                            Price = 1250.0
                        },
                        new
                        {
                            Id = 13,
                            CategoryId = 2,
                            Name = "Winner X v2 68zz",
                            Price = 1250.0
                        },
                        new
                        {
                            Id = 14,
                            CategoryId = 2,
                            Name = "Winner X v1 65zz",
                            Price = 1250.0
                        },
                        new
                        {
                            Id = 15,
                            CategoryId = 2,
                            Name = "Winner V1 65zz",
                            Price = 1250.0
                        },
                        new
                        {
                            Id = 16,
                            CategoryId = 2,
                            Name = "Winner V1 74z8",
                            Price = 1250.0
                        },
                        new
                        {
                            Id = 17,
                            CategoryId = 3,
                            Name = "Raider xc 62zz",
                            Price = 1250.0
                        },
                        new
                        {
                            Id = 18,
                            CategoryId = 3,
                            Name = "Raider 150 68zz",
                            Price = 1250.0
                        },
                        new
                        {
                            Id = 19,
                            CategoryId = 3,
                            Name = "Satria 68zz",
                            Price = 1250.0
                        },
                        new
                        {
                            Id = 20,
                            CategoryId = 3,
                            Name = "Satria 71z4",
                            Price = 1250.0
                        });
                });

            modelBuilder.Entity("WebBanHang.Models.OrderDetail", b =>
                {
                    b.HasOne("WebBanHang.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebBanHang.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("WebBanHang.Models.Product", b =>
                {
                    b.HasOne("WebBanHang.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
